server:
  port: 0

spring:
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER:http://localhost:8090/}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8061/eureka/}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

jmix:
  core:
    available-locales: en
  rest:
    anonymous-url-patterns: /rest/docs/*

main:
  datasource:
    url: jdbc:hsqldb:file:.jmix/hsqldb/depa
    username: sa
    password:

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    eclipselink:
      logging:
        sql: info
    io:
      jmix: info
    org:
      springframework:
        web: debug

#        core:
#          datastore: info
#          AccessLogger: debug