server:
  port: 8060

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8061/eureka/}

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    org.springframework.web: info
    org.springframework.security: debug

spring:
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER:http://localhost:8090/}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER:http://localhost:8080/auth/}realms/master
#          jwk-set-uri: ${AUTH_SERVER:http://localhost:8080/auth/}realms/master/protocol/openid-connect/certs
#          ${AUTH_SERVER:http://localhost:8080/auth}/realms/master/.well-known/openid-configuration
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: auth-service
        uri: lb://auth-service
        predicates:
        - Path=/auth/**,
        filters:
        - RewritePath=/employee/(?<path>.*), /$\{path}
      - id: employee-service
        uri: lb://employee-service
        predicates:
        - Path=/employee/**,
        filters:
        - RewritePath=/employee/(?<path>.*), /rest/public/$\{path}
        - TokenRelay=
        - RemoveRequestHeader=Cookie
      - id: department-service
        uri: lb://department-service
        predicates:
        - Path=/department/**
        filters:
        - RewritePath=/department/(?<path>.*), /rest/public/$\{path}
        - TokenRelay=
        - RemoveRequestHeader=Cookie
      - id: organization-service
        uri: lb://organization-service
        predicates:
        - Path=/organization/**
        filters:
        - RewritePath=/organization/(?<path>.*), /$\{path}
        - TokenRelay=
        - RemoveRequestHeader=Cookie