server:
  port: 0

spring:
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER:http://localhost:8090/}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_SERVER:http://localhost:8080/auth/}realms/test
#          jwk-set-uri: ${AUTH_SERVER:http://localhost:8080/auth/}realms/master/.well-known/openid-configuration

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8061/eureka/}

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"
  level:
    feign: info
    org.springframework.web: info
    org.springframework.security: debug
    ru.udya.services.organization: info