services:
  admin:
    hostname: admin
    build: ./admin-service/
    ports:
      - "8090:8090"
    mem_limit: 512MB
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 6

  config:
    hostname: config
    build: ./config-service/
    environment:
      - JAVA_OPTS=
        -DADMIN_SERVER=http://admin:8090/
    ports:
      - "8088:8088"
    mem_limit: 512MB
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8088/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 6
    depends_on:
      admin:
        condition: service_healthy
  
  discovery:
    hostname: discovery
    build: ./discovery-service/
    environment:
      - JAVA_OPTS=
        -DADMIN_SERVER=http://admin:8090/
        -DCONFIG_SERVER=http://config:8088/
    ports:
      - "8061:8061"
    mem_limit: 512MB
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8061/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 6
    depends_on:
      config:
        condition: service_healthy

  gateway:
    hostname: gateway
    build: ./gateway-service/
    environment:
      - JAVA_OPTS=
        -DADMIN_SERVER=http://admin:8090/
        -DCONFIG_SERVER=http://config:8088/
        -DEUREKA_SERVER=http://discovery:8061/eureka/
        -DAUTH_SERVER=http://auth:8080/auth/
    ports:
      - "8060:8060"
    mem_limit: 512MB
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8060/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 6
    depends_on:
      discovery:
        condition: service_healthy
      auth:
        condition: service_healthy

  auth:
    hostname: auth
    build: ./auth-service/
    environment:
      - JAVA_OPTS=
        -DADMIN_SERVER=http://admin:8090/
        -DCONFIG_SERVER=http://config:8088/
        -DEUREKA_SERVER=http://discovery:8061/eureka/
    ports:
      - "8080:8080"
    mem_limit: 512MB
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 6
    depends_on:
      discovery:
        condition: service_healthy

  employee:
    hostname: employee
    build: ./employee-service/
    environment:
      - JAVA_OPTS=
        -DADMIN_SERVER=http://admin:8090/
        -DCONFIG_SERVER=http://config:8088/
        -DEUREKA_SERVER=http://discovery:8061/eureka/
        -DAUTH_SERVER=http://auth:8080/auth/
    mem_limit: 512MB
    depends_on:
      gateway:
        condition: service_healthy

  department:
    hostname: department
    build: ./department-service/
    environment:
      - JAVA_OPTS=
        -DADMIN_SERVER=http://admin:8090/
        -DCONFIG_SERVER=http://config:8088/
        -DEUREKA_SERVER=http://discovery:8061/eureka/
        -DAUTH_SERVER=http://auth:8080/auth/
    mem_limit: 512MB
    depends_on:
      gateway:
        condition: service_healthy

  organization:
    hostname: organization
    build: ./organization-service/
    environment:
      - JAVA_OPTS=
        -DADMIN_SERVER=http://admin:8090/
        -DCONFIG_SERVER=http://config:8088/
        -DEUREKA_SERVER=http://discovery:8061/eureka/
        -DAUTH_SERVER=http://auth:8080/auth/
    mem_limit: 512MB
    depends_on:
      gateway:
        condition: service_healthy
  admin-jmix:
    hostname: admin-jmix
    build: ./admin-jmix-service/
    environment:
      - JAVA_OPTS=
        -DADMIN_SERVER=http://admin:8090/
        -DCONFIG_SERVER=http://config:8088/
        -DEUREKA_SERVER=http://discovery:8061/eureka/
        -DAUTH_SERVER=http://auth:8080/auth/
        -DAUTH_SERVER_EXTERNAL=http://localhost:8080/auth/
    ports:
      - "8000:8000"
    mem_limit: 512MB
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8000/actuator/health || exit 1
      interval: 10s
      timeout: 5s
      retries: 6
    depends_on:
      gateway:
        condition: service_healthy