server:
  port: 8088
spring:
  profiles:
    active: native
  boot:
    admin:
      client:
        url: ${ADMIN_SERVER:http://localhost:8090/}
  cloud:
    config:
      allowOverride: true
      overrideNone: true
      overrideSystemProperties: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"
    encoding: "@project.build.sourceEncoding@"
    java:
      version: "@java.version@"
